%YAML:1.0

dataset_path: ./data/KITTI360/2013_05_28_drive_0010

#processing parameters
frame_skip: 0                   # skip frames for processing (0 = process all frames, 1 = skip every other frame, etc.)
start_frame: 0                  # start processing from this frame (0-based index)
end_frame: -1                   # end processing at this frame (-1 = process all frames)

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1408
image_height: 376
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 552.554261
   fy: 552.554261
   cx: 682.049453
   cy: 238.769549

#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.0371783278, -0.0986182135, 0.9944306009,
          -0.9992675562, 0.0053553387, 0.0378902567,
          -0.0090621821, -0.9951109327, -0.0983468786]

#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [1.5752681039, 0.0043914093, 0.6500000000]

#feature traker paprameters
max_cnt: 500            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 1.0  # max solver itration time (ms), to guarantee real time
max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.08          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.004         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.00004         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude
